"""
Generated Content Model.

Stores content generated by the marketing team.
"""

from datetime import datetime, date
from typing import List, Optional, Dict, Any
from enum import Enum
from sqlalchemy import Column, Integer, String, Text, DateTime, Date, JSON, ForeignKey, Boolean
from sqlalchemy.sql import func

from marketing.domain.models.base import MarketingBase


class ContentType(str, Enum):
    """Type of content."""
    POST = "post"
    REEL = "reel"
    STORY = "story"
    CAROUSEL = "carousel"
    VIDEO_SCRIPT = "video_script"
    ARTICLE = "article"


class ContentStatus(str, Enum):
    """Content status in workflow."""
    DRAFT = "draft"
    REVIEW = "review"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class Platform(str, Enum):
    """Social media platform."""
    INSTAGRAM = "instagram"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    LINKEDIN = "linkedin"
    FACEBOOK = "facebook"


class GeneratedContent(MarketingBase):
    """
    Content generated by the marketing team.
    
    Stores the content, visual brief, and workflow status.
    """
    
    __tablename__ = "marketing_content"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Content type and platform
    content_type = Column(String(20), nullable=False)
    """Type: post, reel, story, carousel, video_script, article"""
    
    platform = Column(String(20), nullable=False)
    """Platform: instagram, tiktok, youtube, linkedin, facebook"""
    
    # Content
    title = Column(String(200), nullable=True)
    """Optional title for the content"""
    
    text_content = Column(Text, nullable=False)
    """Main text content (caption, script, etc.)"""
    
    visual_brief = Column(Text, nullable=True)
    """Brief for visual creation (Canva)"""
    
    hashtags = Column(JSON, nullable=True, default=list)
    """List of hashtags"""
    
    # Additional content elements
    hook = Column(Text, nullable=True)
    """Hook/opening line for reels/videos"""
    
    cta = Column(Text, nullable=True)
    """Call to action"""
    
    music_suggestion = Column(String(200), nullable=True)
    """Suggested music/audio for reels"""
    
    # Variations
    variations = Column(JSON, nullable=True, default=list)
    """Alternative versions of the content"""
    
    # Workflow status
    status = Column(String(20), default="draft")
    """Status: draft, review, approved, rejected, published, archived"""
    
    nicole_feedback = Column(Text, nullable=True)
    """Feedback from Nicole"""
    
    # Scheduling
    scheduled_date = Column(Date, nullable=True)
    """Planned publication date"""
    
    scheduled_time = Column(String(10), nullable=True)
    """Planned publication time (HH:MM)"""
    
    published_at = Column(DateTime, nullable=True)
    """Actual publication timestamp"""
    
    # Relationships
    meeting_id = Column(Integer, ForeignKey("marketing_meetings.id"), nullable=True)
    """Meeting that generated this content"""
    
    strategy_id = Column(Integer, ForeignKey("marketing_strategies.id"), nullable=True)
    """Strategy this content belongs to"""
    
    # Canva integration
    canva_design_id = Column(String(100), nullable=True)
    """Canva design ID if created"""
    
    canva_design_url = Column(String(500), nullable=True)
    """URL to Canva design"""
    
    # Timestamps
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "content_type": self.content_type,
            "platform": self.platform,
            "title": self.title,
            "text_content": self.text_content,
            "visual_brief": self.visual_brief,
            "hashtags": self.hashtags,
            "hook": self.hook,
            "cta": self.cta,
            "music_suggestion": self.music_suggestion,
            "variations": self.variations,
            "status": self.status,
            "nicole_feedback": self.nicole_feedback,
            "scheduled_date": self.scheduled_date.isoformat() if self.scheduled_date else None,
            "scheduled_time": self.scheduled_time,
            "published_at": self.published_at.isoformat() if self.published_at else None,
            "meeting_id": self.meeting_id,
            "strategy_id": self.strategy_id,
            "canva_design_id": self.canva_design_id,
            "canva_design_url": self.canva_design_url,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
    
    def get_full_content(self) -> str:
        """
        Get the full content formatted for display.
        
        Returns:
            Formatted content string.
        """
        parts = []
        
        if self.title:
            parts.append(f"**{self.title}**\n")
        
        parts.append(self.text_content)
        
        if self.hashtags:
            parts.append("\n" + " ".join(f"#{h}" for h in self.hashtags))
        
        return "\n".join(parts)
